export const ITO_THEMES: string[] = [
  "Melhores comidas",
  "Filmes mais assustadores",
  "Lugares mais quentes",
  "Animais mais perigosos",
  "Coisas mais caras",
  "Profissões mais estressantes",
  "Séries mais viciantes",
  "Lugares mais frios",
  "Sons mais irritantes",
  "Presentes de aniversário mais desejados",
  "Coisas mais nojentas",
  "Super-heróis mais poderosos",
  "Comidas mais azedas",
  "Trabalhos mais perigosos",
  "Coisas que mais dão sono",
  "Cheiros mais bons",
  "Piores desculpas pra chegar atrasado",
  "Coisas mais difíceis de aprender",
  "Lugares mais barulhentos",
  "Animais mais fofos",
];
